export const AI_PROMPT_CHARACTER_LIMIT = 1000;

export const DEBOUNCE_DELAY = 50;

export const MAX_IMAGE_FILES = 2;
export const MAX_IMAGE_FILE_SIZE = 4 * 1024 * 1024; // 4MB
export const MAX_SVG_FILE_SIZE = 1 * 1024 * 1024; // 1MB

export const COMMUNITY_THEME_TAGS = [
  "colorful",
  "minimal",
  "professional",
  "playful",
  "warm",
  "cool",
  "high-contrast",
  "pastel",
  "earthy",
  "neon",
  "retro",
  "futuristic",
  "nature",
  "monochrome",
  "vibrant",
  "elegant",
  "bold",
  "soft",
  "gradient",
  "flat",
  "glassmorphism",
  "neumorphism",
  "brutalist",
  "corporate",
  "startup",
  "dashboard",
  "e-commerce",
  "portfolio",
  "blog",
  "saas",
  "landing-page",
  "ocean",
  "sunset",
  "forest",
  "candy",
  "midnight",
  "nordic",
  "tropical",
  "autumn",
  "winter",
  "spring",
  "cyberpunk",
  "vintage",
  "art-deco",
  "industrial",
  "zen",
  "accessible",
  "romantic",
  "geometric",
] as const;